env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  install_script:
    - pkg upgrade -y
    - pkg install -y gmake coreutils
  script: |
    MOREFLAGS="-Werror" gmake -j all
    gmake shortest
