name: generic

on:
  pull_request:
    branches: [ dev, master, actionsTest ]

jobs:

  benchmarking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make benchmarking
      run: make benchmarking
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make test 
      run: make test 
  
  gcc-6-7-libzstd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gcc-6 + gcc-7 + libzstdmt compilation
      run: |
        make gcc6install gcc7install
        CC=gcc-6 CFLAGS=-Werror make -j all
        make clean
        CC=gcc-7 CFLAGS=-Werror make -j all
        make clean
        LDFLAGS=-Wl,--no-undefined make -C lib libzstd-mt
        make -C tests zbufftest-dll
    
  gcc-8-asan-ubsan-testzstd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gcc-8 + ASan + UBSan + Test Zstd 
      run: | 
        make gcc8install
        CC=gcc-8 CFLAGS="-Werror" make -j all
        make clean
        CC=gcc-8 make -j uasan-test-zstd </dev/null
